options:
    dynamicSubstitutions: true
    logging: CLOUD_LOGGING_ONLY

substitutions:
    _SERVICE_NAME: 'battlesnake-go'
    _IMAGE_NAME: '${_SERVICE_NAME}'
    _IMAGE_PATH: 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}'
    
steps:
# Run tests and save to file
- name: golang:alpine
  entrypoint: go
  args: ['test', '-v', './...']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '${_IMAGE_PATH}@${COMMIT_SHA}',
    '-t', '${_IMAGE_PATH}:${REF_NAME}',
    '.'
  ]

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '${_SERVICE_NAME}', '--image', '${_IMAGE_PATH}:${REF_NAME}', '--region', '${LOCATION}']